import nodemailer from "nodemailer";
import type { SMTPConfig } from "./types";

export async function sendEmail(
  smtp: SMTPConfig,
  subject: string,
  body: string
): Promise<void> {
  if (!smtp.enabled || !smtp.user || !smtp.pass) {
    console.log("[emailer] SMTP not configured or disabled — skipping.");
    return;
  }

  const transporter = nodemailer.createTransport({
    host: smtp.host,
    port: smtp.port,
    secure: smtp.port === 465,
    auth: { user: smtp.user, pass: smtp.pass },
  });

  const html = body
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/^- (.+)$/gm, "<li>$1</li>")
    .replace(/\n\n/g, "</p><p>")
    .replace(/\n/g, "<br>")
    .replace(/^/, "<p>")
    .replace(/$/, "</p>")
    .replace(/---/g, "<hr>");

  const styledHtml = `<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 680px; margin: 0 auto; padding: 24px; color: #1a1a2e; background: #f9f9fc; }
  h1,h2 { color: #6c5ce7; } h3 { color: #2d2d44; }
  code { background: #eeeef8; padding: 1px 5px; border-radius: 3px; font-family: monospace; }
  ul { padding-left: 20px; } li { margin-bottom: 4px; }
  .footer { margin-top: 32px; font-size: 12px; color: #9999b0; border-top: 1px solid #e0e0f0; padding-top: 12px; }
</style>
</head>
<body>
${html}
<div class="footer">Generated by agentItAll · ${new Date().toLocaleString()}</div>
</body>
</html>`;

  await transporter.sendMail({
    from: `"agentItAll" <${smtp.user}>`,
    to: smtp.toAddress,
    subject,
    text: body,
    html: styledHtml,
  });

  console.log(`[emailer] Email sent to ${smtp.toAddress}`);
}
