import nodemailer from "nodemailer";
import type { SMTPConfig } from "./types";

let etherealTransporter: nodemailer.Transporter | null = null;

async function getEtherealTransporter() {
  if (!etherealTransporter) {
    const testAccount = await nodemailer.createTestAccount();
    etherealTransporter = nodemailer.createTransport({
      host: "smtp.ethereal.email",
      port: 587,
      secure: false,
      auth: { user: testAccount.user, pass: testAccount.pass },
    });
    console.log(`[emailer] Ethereal account created: ${testAccount.user}`);
  }
  return etherealTransporter;
}

function buildHtml(body: string): string {
  const html = body
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/^- (.+)$/gm, "<li>$1</li>")
    .replace(/\n\n/g, "</p><p>")
    .replace(/\n/g, "<br>")
    .replace(/^/, "<p>")
    .replace(/$/, "</p>")
    .replace(/---/g, "<hr>");

  return `<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 680px; margin: 0 auto; padding: 24px; color: #1a1a2e; background: #f9f9fc; }
  h1,h2 { color: #6c5ce7; } h3 { color: #2d2d44; }
  code { background: #eeeef8; padding: 1px 5px; border-radius: 3px; font-family: monospace; }
  ul { padding-left: 20px; } li { margin-bottom: 4px; }
  .footer { margin-top: 32px; font-size: 12px; color: #9999b0; border-top: 1px solid #e0e0f0; padding-top: 12px; }
</style>
</head>
<body>
${html}
<div class="footer">Generated by agentItAll · ${new Date().toLocaleString()}</div>
</body>
</html>`;
}

export interface SendResult {
  etherealUrl?: string;
}

export async function sendEmail(
  smtp: SMTPConfig,
  subject: string,
  body: string
): Promise<SendResult> {
  const html = buildHtml(body);

  // Use Ethereal if SMTP not configured
  if (!smtp.enabled || !smtp.user || !smtp.pass) {
    const transporter = await getEtherealTransporter();
    const info = await transporter.sendMail({
      from: '"agentItAll" <agent@ethereal.email>',
      to: "preview@ethereal.email",
      subject,
      text: body,
      html,
    });
    const url = nodemailer.getTestMessageUrl(info) as string;
    console.log(`[emailer] Ethereal preview URL: ${url}`);
    return { etherealUrl: url };
  }

  const transporter = nodemailer.createTransport({
    host: smtp.host,
    port: smtp.port,
    secure: smtp.port === 465,
    auth: { user: smtp.user, pass: smtp.pass },
  });

  await transporter.sendMail({
    from: `"agentItAll" <${smtp.user}>`,
    to: smtp.toAddress,
    subject,
    text: body,
    html,
  });

  console.log(`[emailer] Email sent to ${smtp.toAddress}`);
  return {};
}
